dist: xenial
language: python

python:
  - 3.6
  - 3.7
  - 3.8
  - 3.9

before_install:
  - pip install poetry==1.0.0b2

install:
  - poetry install

script:
  - poetry run flake8 .
  - poetry run pytest
  - poetry check
  - poetry run pip check
  - poetry run safety check --bare --full-report

after_success:
  - pip install coveralls
  - coveralls

notifications:
  email:
    on_success: never
    on_failure: change
